# Notice the v1beta2 version
apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta2-demo
  title: Test API call
  description: Test API call
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill parameters
      required:
        - para1
      properties:
        name:
          title: para1
          type: string
          description: para1
          ui:autofocus: true
          ui:options:
            rows: 5
    
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: test api
      name: test api 
      action: mycompany:create-file
      input:
        para1: '{{ parameters.name }}'

    # - id: fetch-base
    #   name: Fetch Base
    #   action: fetch:cookiecutter
    #   input:
    #     url: ./template
    #     values:
    #       name: '{{ parameters.name }}'

    # - id: fetch-docs
    #   name: Fetch Docs
    #   action: fetch:plain
    #   input:
    #     targetPath: ./community
    #     url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: 'This is {{ parameters.name }}'
    #     repoUrl: '{{ parameters.repoUrl }}'

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
    #     catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'